### ISSUE TITLE
production server

### ISSUE THREAD

**Issue by tombernas** [dracor-org/poldracor#5]
Hi! We are ready to move to the main server. We have made all the corrections and the validator has accepted them. What are the next steps?

**Comment by lehkost** [comment]
fine by me @cmil

**Comment by cmil** [comment]
The corpus is now online at https://dracor.org/pol.

You may still want to add some content to README.md, maybe at least the information that is also in corpus.xml. Otherwise the link from dracor.org to the Github repo would be a bit pointless.
